%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/Olivialinlin/Documents/Github/workshopProject/rawData/psychology-attributes.xlsx
%    Worksheet: StDev Values
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2015/09/14 16:09:38
clear; close all; clc;
%% Import the data
[~, ~, raw] = xlsread('/Users/Olivialinlin/Documents/Github/workshopProject/rawData/psychology-attributes.xlsx','StDev Values');
raw = raw(:,3:end);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,16);
raw = raw(:,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52]);

%% Replace non-numeric cells with NaN
filedName = raw(1,:);
leaveOut = {'catch','catchAns','subID','subage','submale','subrace'};
[~,indexOut] = setdiff(filedName,leaveOut);
filedName = filedName(indexOut);
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));
data = data(2:end,indexOut);
data(isnan(data)) = 0;
stdAveArr = mean(data,1);

%% Clear temporary variables
clearvars raw cellVectors R data;